use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :pdlink, PdlinkWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :pdlink, Pdlink.Repo,
       adapter: Ecto.Adapters.MySQL,
       pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
       ssl: true,
       url: System.get_env("DATABASE_URL")
import_config "prod.secret.exs"
